sudo: required
services:
  - docker

before_install:
  - docker build -t dominicsalinger/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dominicsalinger/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  name: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-695137032151"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"